services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: userservice_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  user-service:
    image: user-service
    build: .
    ports:
      - "8081:8080"
    environment:
        - SPRING_DATASOURCE_URL=${DB_URL}
        - SPRING_DATASOURCE_USERNAME=${DB_USER}
        - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
        - JWT_SECRET=${JWT_SECRET}
        - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data: