services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: userservice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/userservice_db
      - JWT_SECRET=${JWT_SECRET:J8lmA/2UB0LVetCzCJs0N3alkrts9VgElzDkHMwAo7D0VbagxHadA6I4qsgMIg3p8orKaTFJq6IE35q8oIsFHQ==}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: